[package]
name = "get-adapters-addresses"
version = "0.1.0"
edition = "2024"

[dependencies.windows-sys]
version = "0.59"
features = [
    "Win32_Globalization",
    "Win32_Networking_WinSock",
    "Win32_NetworkManagement_IpHelper",
    "Win32_NetworkManagement_Ndis",
]
